### ISSUE TITLE
Error when uploading one by one

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#221]
```
[13:18:15] Async: Invalid argument(s): Please specify an id for the new element
[13:18:15] #0      OsmChange.toElement (package:every_door/models/amenity.dart:268)
#1      OsmApiHelper._uploadOneByOne (package:every_door/providers/osm_api.dart:306)
<asynchronous suspension>
#2      OsmApiHelper.uploadChanges (package:every_door/providers/osm_api.dart:458)
<asynchronous suspension>
#3      _BrowserPageState.uploadChanges (package:every_door/screens/browser.dart:100)
<asynchronous suspension>
```

osmChange:
```xml
<?xml version="1.0"?>
<osmChange version="0.6" generator="Every Door 0.3.0">
<delete><node id="9761468129" version="1" visible="false" lon="-1.9112528" lat="50.7777777"/></delete>
<delete><node id="9761468128" version="1" visible="false" lon="-1.9112569" lat="50.7777878"/></delete>
<modify><node id="9761419935" version="21" visible="true" lon="-1.9044052" lat="50.7778333">
  <tag k="locked" v="yes"/><tag k="was:barrier" v="gate"/>
</node></modify>
<delete><node id="9761468125" version="1" visible="false" lon="-1.9053167" lat="50.7776668"/></delete>
</osmChange>
```

**Comment by Zverik** [comment]
Fixed in 0.5 (although this issue is from 0.3).
