### ISSUE TITLE
First run on iOS fails in geolocation

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#266]
```
flutter: Async error: A request for location permissions is already running, please wait for it to complete before doing another request.
flutter: #0      GeolocatorApple.requestPermission (package:geolocator_apple/src/geolocator_apple.dart:63:7)
<asynchronous suspension>
#1      GeolocationController._subscribeToPositions (package:every_door/providers/geolocation.dart:74:20)
<asynchronous suspension>
#2      GeolocationController.enableTracking (package:every_door/providers/geolocation.dart:155:7)
<asynchronous suspension>
#3      _LoadingPageState.doInit (package:every_door/screens/loading.dart:62:5)
<asynchronous suspension>
```

**Comment by Zverik** [comment]
Most likely done in 0.6.
