### ISSUE TITLE
Map is looooong

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#271]
https://user-images.githubusercontent.com/766031/174958240-bdba72a5-e82e-4321-80cd-558f58b937e1.mp4

```
Flutter: LateInitializationError: Field '_state@954051772' has already been initialized.

#0      LateError._throwFieldAlreadyInitialized (dart:_internal-patch/internal_patch.dart:194:5)
#1      MapControllerImpl._state= (package:flutter_map/src/map/map.dart:25:23)
#2      MapControllerImpl.state= (package:flutter_map/src/map/map.dart:29:5)
#3      FlutterMapState.initState (package:flutter_map/src/map/flutter_map_state.dart:38:19)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4942:57)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4781:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3817:16)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3551:18)
...
```

**Comment by Zverik** [comment]
This is an upstream issue: https://github.com/fleaflet/flutter_map/issues/1288

**Comment by deevroman** [comment]
It seems to be fixed in 0.7

**Comment by Zverik** [comment]
Ah, I did the fix in my local library cache. The upstream PR is not yet merged. Hence the iOS version must still have the bug.

**Comment by matheusgomesms** [comment]
Yes, I confirm that the 0.8 iOS version still have the bug

**Comment by Zverik** [comment]
Finally done.
