### ISSUE TITLE
country coder error

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#367]
```
Dart Unhandled Exception: Bad state: Please call load() and wait until ready == true before using CountryCoder., stack trace: #0      CountryCoder._checkReady (package:country_coder/src/country_coder.dart:59:7)
E/flutter (  769): #1      CountryCoder.smallestOrMatchingRegion (package:country_coder/src/country_coder.dart:67:5)
E/flutter (  769): #2      CountryCoder.isIn (package:country_coder/src/country_coder.dart:289:21)
E/flutter (  769): #3      _EntrancesPaneState.updateNearest.<anonymous closure> (package:every_door/screens/modes/entrances.dart:120:55)
E/flutter (  769): #4      State.setState (package:flutter/src/widgets/framework.dart:1109:30)
E/flutter (  769): #5      _EntrancesPaneState.updateNearest (package:every_door/screens/modes/entrances.dart:113:5)
```

**Comment by Zverik** [comment]
Done in 1.0.
