### ISSUE TITLE
Catch the invalid locale exception in settings

### ISSUE THREAD

**Issue by Zverik** [Zverik/every_door#654]
```
[01:44:45] Flutter: Invalid argument(s): Invalid locale "eo"
[01:44:45] #0      _throwLocaleError (package:intl/src/intl_helpers.dart:204)
#1      verifiedLocale (package:intl/src/intl_helpers.dart:198)
#2      new _CompactNumberFormat (package:intl/src/intl/compact_number_format.dart:269)
#3      new NumberFormat.compact (package:intl/src/intl/number_format.dart:422)
#4      SettingsPage.build (package:every_door/screens/settings.dart:42)
#5      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:479)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:5409)
```

**Comment by Zverik** [comment]
Done in 4.1.
